// See https://aka.ms/new-console-template for more information
byte byt = 120;
short sh = 2300;
int num1 = 13022;
long lng = 120000;
var add = sh + num1;
var mult = byt*sh;
var sub = add - mult ;
Console.WriteLine("Число типа byte " + byt);
Console.ReadLine();
Console.WriteLine("Число типа short " + sh);
Console.ReadLine();
Console.WriteLine("Число типа int " + num1);
Console.ReadLine();
Console.WriteLine("Число типа long " + lng);
Console.ReadLine();
Console.WriteLine("Операция сложения " + add);
Console.ReadLine();
Console.WriteLine($"Операция сложения внутри {sh + num1}"); ;
Console.ReadLine();
Console.WriteLine("Операция умножения " + mult);
Console.ReadLine();
Console.WriteLine("Операция вычетания " + sub);
Console.ReadLine();
Console.WriteLine("Введите х: ");
string x = Console.ReadLine();
var xx = Convert.ToInt32(x);
var powx3 = Math.Pow(xx, 3);
var powx2 = Math.Pow(xx, 2);
var absx = Math.Abs(xx);
var sinx = Math.Sin(xx);
Console.WriteLine($"abs(x)*sin(x)= {absx * sinx}");
Console.WriteLine($"-6*b+5*d-10*x+15= {-6 * powx3 + 5 * powx2 - 10 * xx + 15}");
Console.WriteLine($"2*Pi*x= {2 * Math.PI * xx}");
Console.WriteLine("Введите y: ");
string y = Console.ReadLine();
var yy = Convert.ToInt32(y);
Console.WriteLine($"max (x,y)= {Math.Max(xx,yy)}");
